name: Deploy Laravel API to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader
      - name: Prepare Production .env file
        run: |
          touch .env
          echo "APP_NAME=AKVistion_API" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=${{ secrets.PROD_APP_KEY }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=${{ secrets.PROD_APP_URL }}" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.PROD_DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ secrets.PROD_DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.PROD_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> .env
          echo "SANCTUM_STATEFUL_DOMAINS=${{ secrets.PROD_FRONTEND_URLS }}" >> .env
          echo "SESSION_DOMAIN=.akvision.net" >> .env
      - name: Deploy Secure App Code
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
        
          exclude: |
            **/public/**
            **/.git*
            **/.git*/**
      - name: Deploy Public Folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./public/
